### ISSUE TITLE
Issue with unclear version number of submodule imgui in BabylonCpp project

### ISSUE THREAD

**Issue by phpix** [samdauwe/webgpu-native-examples#14]
Due to your BabylonCpp project being read now, I can only ask you one question in this project.
What is the external/imgui version in the submodule? After cmake compiles, it prompts that Colors [ImGuiCol_ChildWindowBg] does not exist.

**Comment by phpix** [comment]
Find the answer in your historical questions. There is an official development of the BABYLON NATIVE version. Thank you very much for sharing your code.

**Comment by phpix** [comment]
Thank you very much for sharing your code

**Comment by samdauwe** [comment]
Hi phpix,

indeed, I would recommend to use BABYLON NATIVE version as it is well maintained.

Regarding the imgui version, you will need to go back to a 2019 version:

![afbeelding](https://github.com/user-attachments/assets/81c95e79-17cc-4c62-8e2e-83dfe5478576)

![afbeelding](https://github.com/user-attachments/assets/c6b1ca10-abcd-4418-aceb-e88fc6f731d7)

ImGui v1.85 or a few versions higher might work.

Hope it helps,
Sam

**Comment by phpix** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
